title: Simon # your name (or website title) here
logo:  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>Hi! I’m Simon. Currently, I’m research engineer intern. Where I am Responsible for the development of end-to-end machine learning pipelines for various diagnostic applications such as the detection of snoring sounds based on sound analysis, the analysis of sleep stages and cardiac arrhythmias based on photoplethysmography (PPG) sensor data. <br> 

  <br> I’m very interested in learning something new in the Data science/engineering field. Especially, I enjoy taking MOOC (Massive Open Online Course) when I have free time. Checkout the details of progress here<br>

  
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
